### ISSUE TITLE
Detail page controller: the $ctrl.json value is not computed for xml documents

### ISSUE THREAD

**Issue by maachou** [marklogic-community/slush-marklogic-node#494]
the x2js.xml_str2json function is not converting and XML to JSON.

**Comment by grtjn** [comment]
I have trouble reproducing your issue on my end. Can you elaborate on how you got there?

**Comment by maachou** [comment]
I did a test on the last version under development (npm install -g git://github.com/marklogic/slush-marklogic-node.git)
He is what I got:

console logging the x2js.xml_str2json value:

<img width="575" alt="screen shot 2017-03-29 at 22 10 12" src="https://cloud.githubusercontent.com/assets/879083/24474573/4d36976a-14cd-11e7-9d4a-036d56468488.png">

Results on the details page:

<img width="919" alt="screen shot 2017-03-29 at 22 08 29" src="https://cloud.githubusercontent.com/assets/879083/24474582/58d909ae-14cd-11e7-863c-ea6347938ff6.png">

I loaded the following XML file:


[6a954665-f36c-4784-8c17-895c793b62ef.xml.zip](https://github.com/marklogic/slush-marklogic-node/files/880272/6a954665-f36c-4784-8c17-895c793b62ef.xml.zip)

**Comment by grtjn** [comment]
Ah right. I might have mistakenly looked at json 2 xml instead. Let me check again tomorrow. It is not used by view-file-ng, but could be nice to have correct code in place..

**Comment by grtjn** [comment]
xml2json looks for a json property called `xml` at the top, but that only applies to the sample-data. It should be dropped so that the code becomes more generic. E.g.:
```
ctrl.json = x2js.xml_str2json(doc.data).xml;
```
should be:
```
ctrl.json = x2js.xml_str2json(doc.data);
```
