### ISSUE TITLE
additional privileges needed for app-user

### ISSUE THREAD

**Issue by patrickmcelwee** [marklogic-community/slush-marklogic-node#501]
It looks like we have to add xdmp:invoke-in and xdmp:invoke-modules-change-file to the app-role (otherwise, login fails). I have not tested this yet on the most recent dev work and most recent ML9.

**Comment by grtjn** [comment]
I'd like to investigate this in more detail. We noticed this before, but to me it sounds like a regression in the rest-api..

**Comment by grtjn** [comment]
Closing this until more evidence turns up..
