### ISSUE TITLE
Cannot log in after bad login attempt

### ISSUE THREAD

**Issue by patrickmcelwee** [marklogic-community/slush-marklogic-node#513]
This is related to https://github.com/marklogic-community/slush-marklogic-node/issues/482, which fixed this issue on logout, but not after an initial failed login.

**Comment by grtjn** [comment]
I may have broken it in last release. 1.3.0 or before contained an update to the interceptor that forced a logout at failed login. However, that interfered with login messaging on the ui. So i removed it, but looks like it reintroduced the issue. At failed login the middle tier dhould probably flush the authenticator so next attempt will have to recreate it..

**Comment by patrickmcelwee** [comment]
I created a pull request with a suggested fix.

**Comment by grtjn** [comment]
Ah right. You have a PR for exactly that, thanks!
